__include__: [
  '/home/featurize/zfy/DEIM/configs/dataset/visdrone_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

print_freq: 1000
output_dir: ./outputs/dfine_hgnetv2_s_FBRT_mmasa_down_visdrone_mg

train_dataloader:
  total_batch_size: 2 # total batch size equals to 32 (4 * 8)
  # num_workers: 0
val_dataloader:
  total_batch_size: 2
  # num_workers: 0

remap_mscoco_category: True

model: DEIM_MG

DEIM_MG:
  yaml_path: configs/cfg-improve/dfine-s-FBRT-mmasa-down.yaml

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

DEIMCriterion:
    no_weight_vfl_epoch: 30

# epoch:7->8 ap:0.0362->0.0396  0.0001
# Increase to search for the optimal ema
epoches: 1 # 148 + 4n
train_dataloader:
  total_batch_size: 2
  dataset:
    transforms:
      policy:
        epoch: 1
  collate_fn:
    stop_epoch: 1
    ema_restart_decay: 0.9999
    base_size_repeat: ~

val_dataloader:
  total_batch_size: 2


# trtexec --loadEngine=